// =========================================================================
//  GENERATED REFLECTION FILE — DO NOT EDIT MANUALLY
//  This file is automatically generated by reflection_generator
// =========================================================================

#include "ScriptAPI.hpp"
#include "ecs/components/PhysgunScript.hpp"

#ifdef _WIN32
    #define PLUGIN_API extern "C" __declspec(dllexport)
#else
    #define PLUGIN_API extern "C"
#endif

PLUGIN_API void initPlugin(PluginContext* context) {
    ImGui::SetCurrentContext(context->imguiContext);

    // Register PhysgunScript
    {
        Engine::ComponentReflection refl;
        refl.name = "PhysgunScript";
        refl.fields = {
            { "Kp", Engine::FieldType::Float, offsetof(PhysgunScript, Kp) },
            { "Kd", Engine::FieldType::Float, offsetof(PhysgunScript, Kd) },
            { "holdDistance", Engine::FieldType::Float, offsetof(PhysgunScript, holdDistance) },
            { "isHolding", Engine::FieldType::Bool, offsetof(PhysgunScript, isHolding) },
            { "currentHoldDistance", Engine::FieldType::Float, offsetof(PhysgunScript, currentHoldDistance) },
            { "debugShowRay", Engine::FieldType::Bool, offsetof(PhysgunScript, debugShowRay) },
            { "originEntity", Engine::FieldType::Entity, offsetof(PhysgunScript, originEntity) }
        };
        refl.add = [](Registry& reg, Entity e) { reg.emplace<PhysgunScript>(e, PhysgunScript{}); };
        refl.has = [](Registry& reg, Entity e) { return reg.has<PhysgunScript>(e); };
        refl.remove = [](Registry& reg, Entity e) { reg.remove<PhysgunScript>(e); };
        refl.get = [](Registry& reg, Entity e) { return static_cast<void*>(reg.get<PhysgunScript>(e)); };
        Engine::ComponentReflectionRegistry::getInstance().registerComponent(refl);
    }

    // Register PhysgunSystem
    {
        context->systemManager->addSystem(std::make_shared<PhysgunSystem>(*context->registry, *context->renderer, *context->editorMode));
    }

}

PLUGIN_API void shutdownPlugin(PluginContext* context) {
    // Cleanup logic
}
